import './globals.css'
import Nav from './components/Header/page';
import Footer from './components/Footer/page';
import localFont from 'next/font/local'

const clashDisplay = localFont({
  src: [
    {
      path: '..//public/fonts/ClashDisplay-Semibold.ttf',
    },
  ],
  variable: '--font-clash'
})

const archivo = localFont({
  src: [
    {
      path: '../public/fonts/Archivo-Regular.ttf',
    },
  ],
  variable: '--font-archivo'
})


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${clashDisplay.variable} ${archivo.variable}`}>
      <body className=''>
        <Nav />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
